language: C

script:
  - sudo cp libssl.so.1.1 /usr/lib/x86_64-linux-gnu/libssl.so.1.1
  - sudo cp libcrypto.so.1.1 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
  - sudo cp libc.so.6 /lib/x86_64-linux-gnu/libc.so.6

  - openssl version
  - whereis libcrypto
  - ldd irromion

  - ./irromion
