language: C

script:
  - sudo apt remove libc6
  - sudo apt install libc6
  - apt-cache policy libc6
  - sudo apt-get update
  - sudo apt-get upgrade --fix-missing
  - apt-cache policy libc6
  - ldd irromion
  - LD_LIBRARY_PATH=`pwd` ./irromion
