language: C

script:
  - MY_PATH=`pwd`
  - cd /tmp
  - tar xvf openssl-1.1.1.tar.gz
  - cd openssl-1.1.1
  - sudo ./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'
  - sudo make --jobs=4
  - sudo make install
  - cd ${MY_PATH}

  - openssl version
  
  - ./irromion
